### ISSUE TITLE
File packed incorrectly

### ISSUE THREAD

**Issue by sadhukar** [nate-sheltry/Mod-Manager-Fix#1]
Hi, I think the v0.2 release of your fix isn't packing correctly. After downloading on windows I get a "compressed file is not valid" error

**Comment by Immortalshield** [comment]
> Hi, I think the v0.2 release of your fix isn't packing correctly. After downloading on windows I get a "compressed file is not valid" error

same issue here

**Comment by nate-sheltry** [comment]
https://github.com/nate-sheltry/BG3_ModManager_Fix
New repository, fixed the packing issue, sorry.
